### ISSUE TITLE
Set up circle-ci for easy review of PRs

### ISSUE THREAD

**Issue by dpshelio** [carpentries-i18n/i18n-handbook#2]
Circle-ci allows the preview of artifacts, like the output of the docs.
Add the circle-ci script to make this work.
See for example the documentation built on [sunpy](https://github.com/sunpy/sunpy/tree/master/.circleci)

**Comment by akielbowicz** [comment]
Hi @dpshelio, I'd like to help with this. I've never worked with circle-ci, but I will give it a try.

By the way, there is a typo in the description above. The ending square bracket should be a parenthesis.

**Comment by dpshelio** [comment]
Hi @akielbowicz sorry I've not seen this eaerlier!! I'm reviewing #6 now :) - Thanks!!

**Comment by dpshelio** [comment]
Closed by #6
